version: "3.9"

services:
  datt-api:
    container_name: datt-api
    build:
      context: .
      dockerfile: DATT.API/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=DattDb;User=sa;Password=Your_password123;TrustServerCertificate=True"
    networks:
      - datt-network

  sqlserver:
    container_name: datt-sql
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Your_password123"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - datt-network

networks:
  datt-network:

volumes:
  sql_data:
